# Generated by Django 5.1.7 on 2025-03-16 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='description',
            new_name='description_en',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='title',
            new_name='title_en',
        ),
        migrations.AddField(
            model_name='project',
            name='description_ca',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='description_es',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='title_ca',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='title_es',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
