# Generated by Django 5.1.7 on 2025-03-16 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_rename_description_project_description_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='type',
            field=models.CharField(choices=[('design', 'Design'), ('illustration', 'Illustration')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
