# Generated by Django 5.1.7 on 2025-04-01 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_remove_project_image_resources_projectimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
