# Generated by Django 5.1.7 on 2025-04-01 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255)),
                ('text_en', models.CharField(max_length=255)),
                ('text_es', models.CharField(max_length=255)),
                ('text_ca', models.CharField(max_length=255)),
            ],
        ),
    ]
