# Generated by Django 5.1.7 on 2025-04-13 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0002_alter_translation_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translation',
            name='text_ca',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='translation',
            name='text_en',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='translation',
            name='text_es',
            field=models.TextField(),
        ),
    ]
